# -*- coding: utf-8 -*-
"""Constant values

:copyright: Copyright (c) 2021 RadiaSoft LLC.  All Rights Reserved.
:license: http://www.apache.org/licenses/LICENSE-2.0.html
"""
import re
from pykern.pkcollections import PKDict

#: Http auth header name
AUTH_HEADER = "Authorization"

#: http auth header scheme bearer
AUTH_HEADER_SCHEME_BEARER = "Bearer"

#: POSIT: Matches anything generated by `sirepo.job.unique_key`
_UNIQUE_KEY_CHARS_RE = r"\w+"

AUTH_HEADER_RE = re.compile(
    rf"{AUTH_HEADER_SCHEME_BEARER}\s({_UNIQUE_KEY_CHARS_RE})",
    re.IGNORECASE,
)

JSON_SUFFIX = ".json"

MPI_LOG = "mpi_run.log"

PORT_MAX = 32767
PORT_MIN = 1025

PORT_DEFAULTS = PKDict(
    http=8000,
    jupyterhub=8002,
    nginx_proxy=8080,
    react=3000,
    supervisor=8001,
    uwsgi=8000,
)


SRUNIT_USER_AGENT = "srunit/1.0"

TEST_PORT_RANGE = range(10000, 11000)

#: A standalone unique key
UNIQUE_KEY_RE = re.compile(r"^{}$".format(_UNIQUE_KEY_CHARS_RE))
