name: ci-pull-request
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  ci-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -LsS https://radia.run | bash -s ci-pull-request
